### ISSUE TITLE
small pined extensions' icons and etc issues

### ISSUE THREAD

**Issue by EliaHKM** [BloodyHell619/Kyubi-V2-Dark#3]
Hi,
as the title said 
the icons of the extensions
are too small.

![Screenshot_2024-12-23_08-55-04](https://github.com/user-attachments/assets/7aa928ec-74d8-418a-b2be-7d68b16c6356)

also as you can see
the account avatar is not 
on the middle of the 
the button   

on sidebar  (history/bookmarks/sideberry) the icon
is too big
![Screenshot_2024-12-23_09-04-02](https://github.com/user-attachments/assets/f2644f15-5216-4304-8069-479c86885616)

kindly fix them 
thanks

**Comment by walterm128** [comment]
Hi, I fixed it with this code, the size of the addons icons :

In File: `userChrome.css`

Line 1989

I comment 4 lines and add `height: 100% !important;`

```css
.webextension-browser-action > .toolbarbutton-badge-stack > .toolbarbutton-icon {
    filter: grayscale(100%);
    box-shadow: 0 1px 3px rgba(0, 0, 0, 0.50), 0 0 0 1px #4040405c inset !important;
    transition: filter 0.5s, background-color 0.5s, border-color 0.5s  !important;
/*     scale: 87% !important; */
/*     padding: 6px !important; */
/*     margin-left: 3px !important; */
/*     margin-top: -3px !important; */
    height: 100% !important;
    background-color: #551a2b !important;
    border-radius: 2px !important;
    border: 1px solid #181818 !important;
    box-shadow: 0 1px 3px rgba(0, 0, 0, 0.50), 0 0 0 1px #4040405c inset !important;
}
```

**Comment by sinewavess** [comment]
> Hi, I fixed it with this code, the size of the addons icons :
> 
> In File: `userChrome.css`
> 
> Line 1989
> 
> I comment 4 lines and add `height: 100% !important;`
> 
> .webextension-browser-action > .toolbarbutton-badge-stack > .toolbarbutton-icon {
>     filter: grayscale(100%);
>     box-shadow: 0 1px 3px rgba(0, 0, 0, 0.50), 0 0 0 1px #4040405c inset !important;
>     transition: filter 0.5s, background-color 0.5s, border-color 0.5s  !important;
> /*     scale: 87% !important; */
> /*     padding: 6px !important; */
> /*     margin-left: 3px !important; */
> /*     margin-top: -3px !important; */
>     height: 100% !important;
>     background-color: #551a2b !important;
>     border-radius: 2px !important;
>     border: 1px solid #181818 !important;
>     box-shadow: 0 1px 3px rgba(0, 0, 0, 0.50), 0 0 0 1px #4040405c inset !important;
> }

this did not seem to fix the white cross in the bookmark view for me
